@isTest
private class AlexaRankUpdateOnAccountTest
{
   //This Test method is combined in AccountTriggerTest Class so this test class can be deleted during cleanup efforts
   //[RGaokar 11/12/2021 TP #90961] 
   //For code coverage while deploying commented class AlexaRankUpdateOnAccount
   //This class can be deleted
   @IsTest
    private static void testForCommentedClass() {
        AlexaRankUpdateOnAccount alexaTest = new AlexaRankUpdateOnAccount();
    }
  /* @isTest 
   static void testMethod1(){ 
         
         Account testAccount = new Account();
         testAccount.Name='Test Account record' ;
         testAccount.Website='http://www.essenceofemail.com';
         
        
         Test.StartTest(); 
         insert testAccount;        
         Test.StopTest();
    }*/

}